In [110]:
import pandas as pd
import numpy as np
import seaborn as sns

In [111]:
dataset = pd.read_csv(r'C:\Projects_ciência_dados\project_credit_risk\data\raw\home-credit-default-risk\credit_card_balance.csv')

In [112]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3840312 entries, 0 to 3840311
Data columns (total 23 columns):
 #   Column                      Dtype
---  ------                      -----
 0   SK_ID_PREV                  int64
 1   SK_ID_CURR                  int64
 2   MONTHS_BALANCE              int64
 3   AMT_BALANCE                 float64
 4   AMT_CREDIT_LIMIT_ACTUAL     int64
 5   AMT_DRAWINGS_ATM_CURRENT    float64
 6   AMT_DRAWINGS_CURRENT        float64
 7   AMT_DRAWINGS_OTHER_CURRENT  float64
 8   AMT_DRAWINGS_POS_CURRENT    float64
 9   AMT_INST_MIN_REGULARITY     float64
 10  AMT_PAYMENT_CURRENT         float64
 11  AMT_PAYMENT_TOTAL_CURRENT   float64
 12  AMT_RECEIVABLE_PRINCIPAL    float64
 13  AMT_RECIVABLE               float64
 14  AMT_TOTAL_RECEIVABLE        float64
 15  CNT_DRAWINGS_ATM_CURRENT    float64
 16  CNT_DRAWINGS_CURRENT        int64
 17  CNT_DRAWINGS_OTHER_CURRENT  float64
 18  CNT_DRAWINGS_POS_CURRENT    float64
 19  CNT_INSTALMENT_MATURE_CUM   float64
 20  NAME_CONTRACT_STATUS        object
 21  SK_DPD                      int64
 22  SK_DPD_DEF                  int64
dtypes: float64(15), int64(7), object(1)
memory usage: 673.9+ MB

In [113]:
dataset.shape

(3840312, 23)

In [114]:
dataset.describe()

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,SK_DPD,SK_DPD_DEF
count,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.840312e+06,3.090496e+06,3.840312e+06,3.090496e+06,3.090496e+06,3.535076e+06,...,3.840312e+06,3.840312e+06,3.840312e+06,3.090496e+06,3.840312e+06,3.090496e+06,3.090496e+06,3.535076e+06,3.840312e+06,3.840312e+06
mean,1.904504e+06,2.783242e+05,-3.452192e+01,5.830016e+04,1.538080e+05,5.961325e+03,7.433388e+03,2.881696e+02,2.968805e+03,3.540204e+03,...,5.596588e+04,5.808881e+04,5.809829e+04,3.094490e-01,7.031439e-01,4.812496e-03,5.594791e-01,2.082508e+01,9.283667e+00,3.316220e-01
std,5.364695e+05,1.027045e+05,2.666775e+01,1.063070e+05,1.651457e+05,2.822569e+04,3.384608e+04,8.201989e+03,2.079689e+04,5.600154e+03,...,1.025336e+05,1.059654e+05,1.059718e+05,1.100401e+00,3.190347e+00,8.263861e-02,3.240649e+00,2.005149e+01,9.751570e+01,2.147923e+01
min,1.000018e+06,1.000060e+05,-9.600000e+01,-4.202502e+05,0.000000e+00,-6.827310e+03,-6.211620e+03,0.000000e+00,0.000000e+00,0.000000e+00,...,-4.233058e+05,-4.202502e+05,-4.202502e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.434385e+06,1.895170e+05,-5.500000e+01,0.000000e+00,4.500000e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00
50%,1.897122e+06,2.783960e+05,-2.800000e+01,0.000000e+00,1.125000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+01,0.000000e+00,0.000000e+00
75%,2.369328e+06,3.675800e+05,-1.100000e+01,8.904669e+04,1.800000e+05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.633911e+03,...,8.535924e+04,8.889949e+04,8.891451e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.200000e+01,0.000000e+00,0.000000e+00
max,2.843496e+06,4.562500e+05,-1.000000e+00,1.505902e+06,1.350000e+06,2.115000e+06,2.287098e+06,1.529847e+06,2.239274e+06,2.028820e+05,...,1.472317e+06,1.493338e+06,1.493338e+06,5.100000e+01,1.650000e+02,1.200000e+01,1.650000e+02,1.200000e+02,3.260000e+03,3.260000e+03

In [115]:
dataset.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE',
       'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT',
       'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT',
       'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY',
       'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT',
       'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE',
       'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT',
       'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT',
       'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD',
       'SK_DPD_DEF'],
      dtype='object')

Definição de porcentagem de nulos para cada coluna

In [116]:
def porcentagem_nulos_df(df):
    return (
        df.isnull()
          .mean()
          .mul(100)
          .reset_index()
          .rename(columns={'index': 'coluna', 0: 'porcentagem_nulos'})
          .sort_values(by='porcentagem_nulos', ascending=True)
    )

In [117]:
pn = porcentagem_nulos_df(dataset)
pn

                        coluna  porcentagem_nulos
0                   SK_ID_PREV           0.000000
1                   SK_ID_CURR           0.000000
2               MONTHS_BALANCE           0.000000
3                  AMT_BALANCE           0.000000
4      AMT_CREDIT_LIMIT_ACTUAL           0.000000
6         AMT_DRAWINGS_CURRENT           0.000000
14        AMT_TOTAL_RECEIVABLE           0.000000
11   AMT_PAYMENT_TOTAL_CURRENT           0.000000
13               AMT_RECIVABLE           0.000000
12    AMT_RECEIVABLE_PRINCIPAL           0.000000
22                  SK_DPD_DEF           0.000000
16        CNT_DRAWINGS_CURRENT           0.000000
20        NAME_CONTRACT_STATUS           0.000000
21                      SK_DPD           0.000000
9      AMT_INST_MIN_REGULARITY           7.948208
19   CNT_INSTALMENT_MATURE_CUM           7.948208
5     AMT_DRAWINGS_ATM_CURRENT          19.524872
15    CNT_DRAWINGS_ATM_CURRENT          19.524872
8     AMT_DRAWINGS_POS_CURRENT          19.524872
7   AMT_DRAWINGS_OTHER_CURRENT          19.524872
18    CNT_DRAWINGS_POS_CURRENT          19.524872
17  CNT_DRAWINGS_OTHER_CURRENT          19.524872
10         AMT_PAYMENT_CURRENT          19.998063

In [118]:
dataset.isnull().sum()

SK_ID_PREV                         0
SK_ID_CURR                         0
MONTHS_BALANCE                     0
AMT_BALANCE                        0
AMT_CREDIT_LIMIT_ACTUAL            0
AMT_DRAWINGS_ATM_CURRENT      749816
AMT_DRAWINGS_CURRENT               0
AMT_DRAWINGS_OTHER_CURRENT    749816
AMT_DRAWINGS_POS_CURRENT      749816
AMT_INST_MIN_REGULARITY       305236
AMT_PAYMENT_CURRENT           767988
AMT_PAYMENT_TOTAL_CURRENT          0
AMT_RECEIVABLE_PRINCIPAL           0
AMT_RECIVABLE                      0
AMT_TOTAL_RECEIVABLE               0
CNT_DRAWINGS_ATM_CURRENT      749816
CNT_DRAWINGS_CURRENT               0
CNT_DRAWINGS_OTHER_CURRENT    749816
CNT_DRAWINGS_POS_CURRENT      749816
CNT_INSTALMENT_MATURE_CUM     305236
NAME_CONTRACT_STATUS               0
SK_DPD                             0
SK_DPD_DEF                         0
dtype: int64

In [119]:
dataset

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840307,1036507,328243,-9,0.000,45000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840308,1714892,347207,-9,0.000,45000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840309,1302323,215757,-9,275784.975,585000,270000.0,270000.0,0.0,0.0,2250.000,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
3840310,1624872,430337,-10,0.000,450000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840311,2411345,236760,-10,0.000,157500,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

In [120]:
dataset['SK_ID_CURR'].value_counts()

SK_ID_CURR
186401    192
311118    178
120076    140
128827    129
246089    128
         ...
304318      1
359275      1
405801      1
135005      1
438104      1
Name: count, Length: 103558, dtype: int64

Mediana de 22 clientes iguais

In [121]:
dataset.groupby('SK_ID_CURR').size().median()

np.float64(22.0)

- Saldo (limite) máximo para pegar recorrência, bom histórico de pagamento e renda
- Desvio padrão para entender estabilidade dos limites dos cartões
- Mean para entender resumir os saldos dos cartões
- Colocar Last para entender o último saldo do cartão

In [122]:
dataset_agg = dataset.groupby('SK_ID_CURR')['AMT_BALANCE'].agg(
    AMT_BALANCE_BIGGER = 'max',
    AMT_BALANCE_STD = 'std',
    AMT_BALANCE_MEAN = 'mean'
)

In [123]:
last_balance = (
    dataset
    .sort_values(['SK_ID_CURR','MONTHS_BALANCE'])
    .groupby('SK_ID_CURR')
    .tail(1)[['SK_ID_CURR','AMT_BALANCE']]
    .rename(columns={'AMT_BALANCE':'AMT_BALANCE_LAST'})
)

last_balance

         SK_ID_CURR  AMT_BALANCE_LAST
584804       100006             0.000
2739019      100011             0.000
2673656      100013             0.000
1278805      100021             0.000
778090       100023             0.000
...             ...               ...
76410        456244             0.000
2017416      456246            62.685
1148019      456247             0.000
735902       456248             0.000
140639       456250        153832.725

[103558 rows x 2 columns]

In [124]:
dataset_agg

            AMT_BALANCE_BIGGER  AMT_BALANCE_STD  AMT_BALANCE_MEAN
SK_ID_CURR
100006                   0.000         0.000000          0.000000
100011              189000.000     68127.238270      54482.111149
100013              161420.220     43237.406997      18159.919219
100021                   0.000         0.000000          0.000000
100023                   0.000         0.000000          0.000000
...                        ...              ...               ...
456244              453627.675    181540.706436     131834.730732
456246               43490.115     18263.381378      13136.731875
456247              190202.130     56576.242229      23216.396211
456248                   0.000         0.000000          0.000000
456250              200208.915     12914.006678     173589.326250

[103558 rows x 3 columns]

In [125]:
last_balance = last_balance.set_index('SK_ID_CURR')

dataset_agg = dataset_agg.join(last_balance)

In [126]:
dataset_agg

,AMT_BALANCE_BIGGER,AMT_BALANCE_STD,AMT_BALANCE_MEAN,AMT_BALANCE_LAST
SK_ID_CURR,,,,
100006,0.000,0.000000,0.000000,0.000
100011,189000.000,68127.238270,54482.111149,0.000
100013,161420.220,43237.406997,18159.919219,0.000
100021,0.000,0.000000,0.000000,0.000
100023,0.000,0.000000,0.000000,0.000
...,...,...,...,...
456244,453627.675,181540.706436,131834.730732,0.000
456246,43490.115,18263.381378,13136.731875,62.685
456247,190202.130,56576.242229,23216.396211,0.000
456248,0.000,0.000000,0.000000,0.000
456250,200208.915,12914.006678,173589.326250,153832.725